### ISSUE TITLE
NumFOCUS board meeting minutes not available, incomplete

### ISSUE THREAD

**Issue by ivanov** [numfocus/TownHall#4]
I am trying to understand how the NumFOCUS board and staff arrived at the new proposed direction, but unfortunately there are no publicly posted board meeting minutes since May 2023. There were 24 meetings the year prior (2022) but in 2023 we only have meeting notes for 8. And of the meetings that do have minutes, aside from attendance information, they appear to be just the agenda that was used for planning, rather than any capture of discussion and decisions made.

https://numfocus.github.io/numfocus-board/2023/

**Comment by ivanov** [comment]
NumFOCUS board member Logan Kilpatrick (previously secretary now president) has acknowledged responsibility for posting the board meeting minutes. The [board meeting minutes for 2023](https://numfocus.github.io/numfocus-board/2023/) have now been posted.

**Comment by logankilpatrick** [comment]
Will have 2024 minutes updated soon!

**Comment by logankilpatrick** [comment]
Also, to be clear, we are not going in a net new direction, this is a continuation of our existing mission just with some added fundraising mechanisms. More details forthcoming!

**Comment by ivanov** [comment]
[2024 minutes got updated](https://numfocus.github.io/numfocus-board/2024/), thank you @logankilpatrick .

However, there is still a challenge with how light they are on content, context, motions, proposals, and so on. I want to re-iterate from the original message.

> And of the meetings that do have minutes, aside from attendance information, they appear to be just the agenda that was used for planning, rather than any capture of discussion and decisions made.

**Comment by aterrel** [comment]
This issue seems to be complete. The board published their minutes, albeit not in the form requested but according to their policy. Will close for now but feel free to reopen if there is anything else to add here.
