### ISSUE TITLE
NumFOCUS board history missing after 2019

### ISSUE THREAD

**Issue by ivanov** [numfocus/TownHall#5]
I'd like to better understand the leadership changes at the NumFOCUS Board of Directors over the years, but [the historical information available](https://numfocus.org/board-history) stops at 2019.  I will try to reconstruct from meeting minutes.

**Comment by logankilpatrick** [comment]
Updated the meeting minutes which should help!

**Comment by aterrel** [comment]
closing as this history has been updated. Please open if you feel it is inadequate in any form.
